In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load Dataset
df = pd.read_csv("raw/automobileEDA_dirty_training.csv")
pd.set_option("display.max_columns",None)
df

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,2025-01-01,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,0.890278,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,02/01/2025,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,0.890278,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,01-03-2025,1,122,ALFA-ROMERO,std,two,hatchback,rwd,front,94.5,0.822681,0.909722,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,04-Jan-2025,2,164,audi,std,four,sedan,fwd,front,99.8,0.848630,0.919444,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2025-01-05,2,164,audi,std,four,sedan,4wd,front,99.4,0.848630,0.922222,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,2025-07-20,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,0.907256,0.956944,55.5,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0,12.368421,Medium,0,1
201,06/01/2025,2,122,audi,std,two,sedan,fwd,front,99.8,0.851994,0.920833,53.1,2507,ohc,five,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250.0,12.368421,Medium,0,1
202,26/01/2025,1,148,dodge,std,four,sedan,fwd,front,93.7,0.755887,0.886111,50.6,1989,ohc,four,90,2bbl,2.97,3.23,9.4,68.0,5500.0,31,38,7609.0,7.580645,Low,0,1
203,2025-03-02,0,122,mazda,std,four,sedan,fwd,front,98.8,0.854397,0.923611,55.5,2443,ohc,four,122,idi,3.39,3.39,22.7,64.0,4650.0,36,42,10795.0,6.527778,Low,1,0
204,2025-04-11,0,108,NaN,std,four,sedan,fwd,front,100.4,0.887074,0.923611,55.1,3060,ohcv,six,181,mpfi,3.43,3.27,9.0,152.0,5200.0,19,25,13499.0,12.368421,Medium,0,1

In [3]:
# Menunjukkan 5 data pertama
df.head(5)

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,2025-01-01,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,0.890278,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,02/01/2025,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,0.890278,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,01-03-2025,1,122,ALFA-ROMERO,std,two,hatchback,rwd,front,94.5,0.822681,0.909722,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,04-Jan-2025,2,164,audi,std,four,sedan,fwd,front,99.8,0.848630,0.919444,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2025-01-05,2,164,audi,std,four,sedan,4wd,front,99.4,0.848630,0.922222,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1

In [4]:
# Menghitung jumlah baris dan kolom
sum_baris = len(df.index)
sum_kolom = len(df.columns)
print(f"jumlah baris pada dataframe ini adalah {sum_baris} dan jumlah kolom adalah {sum_kolom}")

jumlah baris pada dataframe ini adalah 205 dan jumlah kolom adalah 30

In [5]:
# Informasi data kolom
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_date   203 non-null    str
 1   symboling          205 non-null    int64
 2   normalized-losses  205 non-null    int64
 3   make               203 non-null    str
 4   aspiration         205 non-null    str
 5   num-of-doors       203 non-null    str
 6   body-style         205 non-null    str
 7   drive-wheels       205 non-null    str
 8   engine-location    205 non-null    str
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    str
 15  num-of-cylinders   205 non-null    str
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    str
 18  bore               205 non-null    float64
 19  stroke             201 non-null    float64
 20  compression-ratio  205 non-null    float64
 21  horsepower         202 non-null    float64
 22  peak-rpm           205 non-null    float64
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              202 non-null    float64
 26  city-L/100km       205 non-null    float64
 27  horsepower-binned  204 non-null    str
 28  diesel             205 non-null    int64
 29  gas                205 non-null    int64
dtypes: float64(11), int64(8), str(11)
memory usage: 48.2 KB

In [6]:
df.describe(include="all")

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
count,203,205.000000,205.000000,203,205,203,205,205,205,205.000000,205.000000,205.000000,205.000000,205.000000,205,205,205.000000,205,205.000000,201.000000,205.000000,202.000000,205.000000,205.000000,205.000000,202.000000,205.000000,204,205.000000,205.000000
unique,199,NaN,NaN,27,2,2,7,5,2,NaN,NaN,NaN,NaN,NaN,6,7,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN
top,06/01/2025,NaN,NaN,toyota,std,four,sedan,fwd,front,NaN,NaN,NaN,NaN,NaN,ohc,four,NaN,mpfi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Low,NaN,NaN
freq,2,NaN,NaN,33,169,117,96,121,202,NaN,NaN,NaN,NaN,NaN,148,159,NaN,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117,NaN,NaN
mean,NaN,0.839024,122.058537,NaN,NaN,NaN,NaN,NaN,NaN,98.784878,0.837107,0.915095,53.762927,2554.575610,NaN,NaN,126.980488,NaN,3.329020,3.258209,10.207902,103.403526,5119.515800,25.200000,30.721951,13181.668317,9.939602,NaN,0.102439,0.897561
std,NaN,1.247916,31.748344,NaN,NaN,NaN,NaN,NaN,NaN,6.018632,0.059030,0.028986,2.439080,515.016952,NaN,NaN,41.398466,NaN,0.266929,0.316354,4.064078,37.453870,476.073141,6.446917,6.836734,7924.054951,2.537799,NaN,0.303967,0.303967
min,NaN,-2.000000,65.000000,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,0.678039,0.837500,47.800000,1488.000000,NaN,NaN,61.000000,NaN,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000,4.795918,NaN,0.000000,0.000000
25%,NaN,0.000000,101.000000,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,0.801538,0.890278,52.000000,2169.000000,NaN,NaN,98.000000,NaN,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7778.250000,7.833333,NaN,0.000000,1.000000
50%,NaN,1.000000,122.000000,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,0.832292,0.909722,54.100000,2420.000000,NaN,NaN,120.000000,NaN,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10320.000000,9.791667,NaN,0.000000,1.000000
75%,NaN,2.000000,137.000000,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,0.881788,0.923611,55.500000,2926.000000,NaN,NaN,141.000000,NaN,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16482.500000,12.368421,NaN,0.000000,1.000000
max,NaN,3.000000,256.000000,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,1.000000,1.000000,59.800000,4066.000000,NaN,NaN,326.000000,NaN,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000,18.076923,NaN,1.000000,1.000000

# Temuan data
1. kolom "transaction_date" bertipe data str seharusnya bertipe data tanggal

In [7]:
# melihat data unique

for i in df.columns:
    df_unique = df[i].unique()
    df_data_unique = pd.DataFrame(df_unique, columns = [i])
    display(df_data_unique)

    transaction_date
0         2025-01-01
1         02/01/2025
2         01-03-2025
3        04-Jan-2025
4         2025-01-05
..               ...
195       2025-07-16
196       17/07/2025
197       07-18-2025
198      19-Jul-2025
199       2025-07-20

[200 rows x 1 columns]

   symboling
0          3
1          1
2          2
3          0
4         -1
5         -2

    normalized-losses
0                 122
1                 164
2                 158
3                 192
4                 188
5                 121
6                  98
7                  81
8                 118
9                 148
10                110
11                145
12                137
13                101
14                 78
15                106
16                 85
17                107
18                104
19                113
20                150
21                129
22                115
23                 93
24                142
25                161
26                153
27                125
28                128
29                103
30                168
31                108
32                194
33                231
34                119
35                154
36                 74
37                186
38                 83
39                102
40                 89
41                 87
42                 77
43                 91
44                134
45                 65
46                197
47                 90
48                 94
49                256
50                 95

             make
0     alfa-romero
1     ALFA-ROMERO
2            audi
3             bmw
4       chevrolet
5           dodge
6         dodge
7           honda
8            Audi
9           isuzu
10         jaguar
11          mazda
12  mercedes-benz
13      mercury
14     mitsubishi
15            BMW
16         nissan
17            NaN
18         peugot
19         toyota
20       plymouth
21        porsche
22      porsche
23        renault
24           saab
25         subaru
26     volkswagen
27          volvo

  aspiration
0        std
1      turbo

  num-of-doors
0          two
1         four
2          NaN

    body-style
0  convertible
1    hatchback
2        sedan
3        wagon
4        SEDAN
5        Sedan
6      hardtop

  drive-wheels
0          rwd
1          fwd
2          4wd
3          AWD
4          RWD

  engine-location
0           front
1            rear

    wheel-base
0         88.6
1         94.5
2         99.8
3         99.4
4        105.8
5        101.2
6        103.5
7        110.0
8         88.4
9         93.7
10       103.3
11        95.9
12        86.6
13        96.5
14        94.3
15        96.0
16       113.0
17       102.0
18        93.1
19        95.3
20        98.8
21       104.9
22       106.7
23       115.6
24        96.6
25       120.9
26       112.0
27       102.7
28        93.0
29        96.3
30        95.1
31        97.2
32       100.4
33        91.3
34        99.2
35       107.9
36       114.2
37       108.0
38        89.5
39        96.1
40        99.1
41        93.3
42        97.0
43        96.9
44        95.7
45        98.4
46       102.4
47       102.9
48       104.5
49        97.3
50       104.3
51       109.1

      length
0   0.811148
1   0.822681
2   0.848630
3   0.851994
4   0.925997
..       ...
68  0.765497
69  0.796252
70  0.865930
71  0.879865
72  0.907256

[73 rows x 1 columns]

       width
0   0.890278
1   0.909722
2   0.919444
3   0.922222
4   0.920833
5   0.991667
6   0.900000
7   0.929167
8   0.943056
9   0.984722
10  0.837500
11  0.883333
12  0.886111
13  0.897222
14  0.887500
15  0.888889
16  0.905556
17  0.868056
18  0.916667
19  0.858333
20  0.966667
21  0.980556
22  0.891667
23  0.912500
24  0.923611
25  0.918056
26  0.976389
27  0.995833
28  0.979167
29  1.000000
30  0.944444
31  0.894444
32  0.908333
33  0.950000
34  0.948611
35  0.902778
36  0.925000
37  0.880556
38  0.911111
39  0.940278
40  0.933333
41  0.956944
42  0.955556

    height
0     48.8
1     52.4
2     54.3
3     53.1
4     55.7
5     55.9
6     53.7
7     56.3
8     53.2
9     52.0
10    50.8
11    50.6
12    59.8
13    50.2
14    52.6
15    54.5
16    58.3
17    53.3
18    54.1
19    51.0
20    53.5
21    51.4
22    52.8
23    47.8
24    49.6
25    55.5
26    54.4
27    56.5
28    58.7
29    54.9
30    56.7
31    55.4
32    54.8
33    49.4
34    51.6
35    54.7
36    55.1
37    56.1
38    49.7
39    56.0
40    55.2
41    50.5
42    52.5
43    53.0
44    59.1
45    53.9
46    55.6
47    56.2
48    57.5

     curb-weight
0           2548
1           2823
2           2337
3           2824
4           2507
..           ...
164         2952
165         3049
166         3012
167         3217
168         3062

[169 rows x 1 columns]

  engine-type
0        dohc
1        ohcv
2         ohc
3           l
4       rotor
5        ohcf

  num-of-cylinders
0             four
1              six
2             five
3            three
4           twelve
5              two
6            eight

    engine-size
0           130
1           152
2           109
3           136
4           131
5           108
6           164
7           209
8            61
9            90
10           98
11          122
12          156
13           92
14           79
15          110
16          111
17          119
18          258
19          326
20           91
21           70
22           80
23          140
24          134
25          183
26          234
27          308
28          304
29           97
30          103
31          120
32          181
33          151
34          194
35          132
36          121
37          146
38          171
39          161
40          141
41          173
42          145

  fuel-system
0        mpfi
1        2bbl
2        MPFI
3         mfi
4        1bbl
5        spfi
6        4bbl
7         idi
8        Mpfi
9        spdi

        bore
0   3.470000
1   2.680000
2   3.190000
3   3.130000
4   3.500000
5   3.310000
6   3.620000
7   2.910000
8   3.030000
9   2.970000
10  3.340000
11  3.600000
12  2.920000
13  3.150000
14  3.430000
15  3.630000
16  3.540000
17  3.080000
18  3.329751
19  3.390000
20  3.760000
21  3.580000
22  3.460000
23  3.800000
24  3.780000
25  3.170000
26  3.350000
27  3.590000
28  2.990000
29  3.330000
30  3.700000
31  3.610000
32  3.940000
33  3.740000
34  2.540000
35  3.050000
36  3.270000
37  3.240000
38  3.010000

    stroke
0     2.68
1     3.47
2     3.40
3     2.80
4     3.19
5     3.39
6     3.03
7     3.11
8     3.23
9     3.46
10    3.90
11    3.41
12    3.07
13    3.58
14    4.17
15    2.76
16    3.15
17     NaN
18    3.16
19    3.64
20    3.10
21    3.35
22    3.12
23    3.86
24    3.29
25    3.27
26    3.52
27    2.19
28    3.21
29    2.90
30    2.07
31    2.36
32    2.64
33    3.08
34    3.50
35    3.54
36    2.87

    compression-ratio
0                9.00
1               10.00
2                8.00
3                8.50
4                8.30
5                8.80
6                9.50
7                9.60
8                9.41
9                9.40
10               7.60
11               7.00
12               9.20
13              10.10
14               9.10
15               8.10
16              11.50
17               8.60
18              22.70
19              22.00
20              21.50
21               7.50
22              21.90
23               7.80
24               8.40
25              21.00
26               8.70
27               9.31
28               9.30
29               7.70
30              22.50
31              23.00

    horsepower
0   111.000000
1   154.000000
2   102.000000
3   115.000000
4   110.000000
5   140.000000
6   101.000000
7   121.000000
8   182.000000
9    48.000000
10   70.000000
11         NaN
12   68.000000
13   88.000000
14  145.000000
15   58.000000
16   76.000000
17   60.000000
18   86.000000
19  100.000000
20   78.000000
21   90.000000
22  176.000000
23  262.000000
24   84.000000
25   64.000000
26  120.000000
27   72.000000
28  123.000000
29  155.000000
30  184.000000
31  175.000000
32  116.000000
33   69.000000
34   55.000000
35   97.000000
36  152.000000
37  160.000000
38  200.000000
39   95.000000
40  142.000000
41  143.000000
42  207.000000
43  104.256158
44   73.000000
45   82.000000
46   94.000000
47   62.000000
48   56.000000
49  112.000000
50   92.000000
51  161.000000
52  156.000000
53   52.000000
54   85.000000
55  114.000000
56  162.000000
57  134.000000
58  106.000000

       peak-rpm
0   5000.000000
1   5500.000000
2   5800.000000
3   4250.000000
4   5400.000000
5   5100.000000
6   4800.000000
7   6000.000000
8   4750.000000
9   4650.000000
10  4200.000000
11  4350.000000
12  4500.000000
13  5200.000000
14  4150.000000
15  5600.000000
16  5900.000000
17  5125.369458
18  5250.000000
19  4900.000000
20  4400.000000
21  6600.000000
22  5300.000000

    city-mpg
0         21
1         19
2         24
3         18
4         17
5         23
6         20
7         16
8         15
9         47
10        38
11        37
12        31
13        49
14        30
15        27
16        25
17        13
18        26
19        36
20        22
21        14
22        45
23        28
24        32
25        35
26        34
27        29
28        33

    highway-mpg
0            27
1            26
2            30
3            22
4            25
5            20
6            29
7            28
8            53
9            43
10           41
11           38
12           24
13           54
14           42
15           34
16           33
17           31
18           19
19           17
20           23
21           32
22           39
23           18
24           16
25           37
26           50
27           36
28           47
29           46

       price
0    13495.0
1    16500.0
2    13950.0
3    17450.0
4    15250.0
..       ...
180  16845.0
181  19045.0
182  21485.0
183  22470.0
184  22625.0

[185 rows x 1 columns]

    city-L/100km
0      11.190476
1      12.368421
2       9.791667
3      13.055556
4      13.823529
5      10.217391
6      11.750000
7      14.687500
8      15.666667
9       5.000000
10      6.184211
11      6.351351
12      7.580645
13      4.795918
14      7.833333
15      8.703704
16      9.400000
17     18.076923
18      9.038462
19      6.527778
20     10.681818
21     16.785714
22      5.222222
23      8.392857
24      7.343750
25      6.714286
26      6.911765
27      8.103448
28      7.121212

  horsepower-binned
0            Medium
1               Low
2              High
3               NaN

   diesel
0       0
1       1

   gas
0    1
1    0

In [8]:
# Ganti value pada kolom "num-of-doors" jadi int

num_doors_map = {"two":2, "four":4}

df['num-of-doors']=df['num-of-doors'].map(num_doors_map)

In [9]:
# Ganti value pada kolom "num-of-cylinders"

num_cylinder_map = {"four":4, "six":6, "five":5, "three":3, "twelve":12, "two":2, "eight":8}
df['num-of-cylinders']=df['num-of-cylinders'].map(num_cylinder_map)

# Terdapat beberapa catetan
1. Pada kolom tanggal masih ambigu format tanggal nya
2. Pada kolom make, penulisan "ALFA-ROMERO" dan "alfa-romero", "alfa-romero" juga masih ada spasi di depannya, penulisan "Audi" dan "audi". "mercury" , "dodge" nilainya dan "porche" masih ada spasi juga. penulisan "bmw" dan "BMW" juga ada beda. masih ada value NaN
3. kolom "num-of-doors" terdapat kolom NaN
4. kolom "body-style" value "sedan" ada yang tulisannya "sedan" dan "SEDAN"
5. kolom "drive-wheels" value "rwd" dan "RWD"
6. kolom "fuel-system" ada yang value nya "mpfi", "MPFI", "Mpfi"
7. Kolom bore jadi "int" aja daripada "float"
8. Kolom "bore" itu tipe nya int
9. Kolom "stroke" ada NaN juga
10. Kolom "horse power" ada "NaN"
11. Kolom "peak-rpm" itu formatnya jadi int
12. Kolom "horsepower-binned" ada "NaN"

In [10]:
# finding duplicate
df_dup = len(df.duplicated())
print (f" Jumlah data duplicated sebanyak {df_dup} data")

 Jumlah data duplicated sebanyak 205 data

In [11]:
# Menecari tau nilai persentase null values disetiap kolom
df.isna().sum()/len(df)*100

transaction_date     0.975610
symboling            0.000000
normalized-losses    0.000000
make                 0.975610
aspiration           0.000000
num-of-doors         0.975610
body-style           0.000000
drive-wheels         0.000000
engine-location      0.000000
wheel-base           0.000000
length               0.000000
width                0.000000
height               0.000000
curb-weight          0.000000
engine-type          0.000000
num-of-cylinders     0.000000
engine-size          0.000000
fuel-system          0.000000
bore                 0.000000
stroke               1.951220
compression-ratio    0.000000
horsepower           1.463415
peak-rpm             0.000000
city-mpg             0.000000
highway-mpg          0.000000
price                1.463415
city-L/100km         0.000000
horsepower-binned    0.487805
diesel               0.000000
gas                  0.000000
dtype: float64

In [12]:
df.loc[df.isnull().any(axis = 1)]

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
10,01-11-2025,0,192,bmw,std,4.0,sedan,rwd,front,101.2,0.849592,0.900000,54.3,2395,ohc,4,108,mpfi,3.500000,2.80,8.80,101.0,5800.0,23,29,NaN,10.217391,Low,0,1
15,16-Jan-2025,0,122,bmw,std,NaN,sedan,rwd,front,103.5,0.931283,0.943056,53.7,3380,ohc,6,209,mpfi,3.620000,3.39,8.00,182.0,5400.0,16,22,41315.0,14.687500,High,0,1
20,2025-01-21,1,118,dodge,std,2.0,hatchback,fwd,front,93.7,0.755887,0.886111,50.8,1876,ohc,4,90,2bbl,2.970000,3.23,9.41,NaN,5500.0,37,41,5572.0,6.351351,Low,0,1
35,05-Feb-2025,0,78,honda,std,4.0,wagon,fwd,front,96.5,0.754926,0.887500,58.3,2024,ohc,4,92,1bbl,2.920000,3.41,9.20,76.0,6000.0,30,34,NaN,7.833333,Low,0,1
40,NaN,0,85,honda,std,4.0,sedan,fwd,front,96.5,0.842864,0.905556,54.1,2465,ohc,4,110,mpfi,3.150000,3.58,9.00,101.0,5800.0,24,28,12945.0,9.791667,Low,0,1
46,02-16-2025,0,122,jaguar,std,2.0,sedan,rwd,front,102.0,0.921192,0.980556,47.8,3950,ohcv,12,326,mpfi,3.540000,2.76,11.50,262.0,5000.0,13,17,36000.0,18.076923,NaN,0,1
52,2025-02-22,3,150,mazda,std,2.0,hatchback,rwd,front,95.3,0.812110,0.912500,49.6,2380,rotor,2,70,4bbl,3.329751,NaN,9.40,101.0,6000.0,17,23,10945.0,13.823529,Low,0,1
53,23/02/2025,3,150,mazda,std,2.0,hatchback,rwd,front,95.3,0.812110,0.912500,49.6,2380,rotor,2,70,4bbl,3.329751,NaN,9.40,101.0,6000.0,17,23,11845.0,13.823529,Low,0,1
54,02-24-2025,3,150,mazda,std,2.0,hatchback,rwd,front,95.3,0.812110,0.912500,49.6,2385,rotor,2,70,4bbl,3.329751,NaN,9.40,101.0,6000.0,17,23,13645.0,13.823529,Low,0,1
55,25-Feb-2025,3,150,mazda,std,2.0,hatchback,rwd,front,95.3,0.812110,0.912500,49.6,2500,rotor,2,80,mpfi,3.329751,NaN,9.40,NaN,6000.0,16,23,15645.0,14.687500,Medium,0,1
70,03-12-2025,0,122,mercedes-benz,std,NaN,sedan,rwd,front,120.9,1.000000,0.995833,56.7,3900,ohcv,8,308,mpfi,3.800000,3.35,8.00,184.0,4500.0,14,16,40960.0,16.785714,High,0,1
80,2025-03-22,3,122,mitsubishi,turbo,2.0,hatchback,fwd,front,95.9,0.832292,0.920833,50.2,2921,ohc,4,156,spdi,3.590000,3.86,7.00,145.0,5000.0,19,24,NaN,12.368421,Medium,0,1
100,2025-04-11,0,108,NaN,std,4.0,sedan,fwd,front,100.4,0.887074,0.923611,55.1,3060,ohcv,6,181,mpfi,3.430000,3.27,9.00,152.0,5200.0,19,25,13499.0,12.368421,Medium,0,1
120,2025-05-01,-1,74,plymouth,std,4.0,wagon,fwd,front,103.3,0.839020,0.897222,59.8,2535,ohc,4,122,2bbl,3.350000,3.46,8.50,NaN,5000.0,24,30,8921.0,9.791667,Low,0,1
140,NaN,0,102,subaru,std,4.0,sedan,4wd,front,97.0,0.826526,0.908333,54.3,2385,ohcf,4,108,2bbl,3.620000,2.64,9.00,82.0,4800.0,24,25,9233.0,9.791667,Low,0,1
204,2025-04-11,0,108,NaN,std,4.0,sedan,fwd,front,100.4,0.887074,0.923611,55.1,3060,ohcv,6,181,mpfi,3.430000,3.27,9.00,152.0,5200.0,19,25,13499.0,12.368421,Medium,0,1

Tindak lanjut dari null values :
1. Persentase null values sangat kecil
2. Null values pada dataframe tidak bisa diisi dengan imputation dikarenakan dikhawatirkan memiliki perbedaan tipe mobil, karena setiap transaksi tidak memberikan unique code dari setiap kendaraan

sehingga --> dilakukan drop values

In [13]:
# Drop Null values
df = df.dropna()
df

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,2025-01-01,3,122,alfa-romero,std,2.0,convertible,rwd,front,88.6,0.811148,0.890278,48.8,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,02/01/2025,3,122,alfa-romero,std,2.0,convertible,rwd,front,88.6,0.811148,0.890278,48.8,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,01-03-2025,1,122,ALFA-ROMERO,std,2.0,hatchback,rwd,front,94.5,0.822681,0.909722,52.4,2823,ohcv,6,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,04-Jan-2025,2,164,audi,std,4.0,sedan,fwd,front,99.8,0.848630,0.919444,54.3,2337,ohc,4,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2025-01-05,2,164,audi,std,4.0,sedan,4wd,front,99.4,0.848630,0.922222,54.3,2824,ohc,5,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,19-Jul-2025,-1,95,volvo,turbo,4.0,sedan,rwd,front,109.1,0.907256,0.956944,55.5,3217,ohc,6,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0,9.038462,Medium,1,0
200,2025-07-20,-1,95,volvo,turbo,4.0,sedan,rwd,front,109.1,0.907256,0.956944,55.5,3062,ohc,4,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0,12.368421,Medium,0,1
201,06/01/2025,2,122,audi,std,2.0,sedan,fwd,front,99.8,0.851994,0.920833,53.1,2507,ohc,5,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250.0,12.368421,Medium,0,1
202,26/01/2025,1,148,dodge,std,4.0,sedan,fwd,front,93.7,0.755887,0.886111,50.6,1989,ohc,4,90,2bbl,2.97,3.23,9.4,68.0,5500.0,31,38,7609.0,7.580645,Low,0,1
203,2025-03-02,0,122,mazda,std,4.0,sedan,fwd,front,98.8,0.854397,0.923611,55.5,2443,ohc,4,122,idi,3.39,3.39,22.7,64.0,4650.0,36,42,10795.0,6.527778,Low,1,0

In [14]:
# Mengubah setting date
df['transaction_date']=pd.to_datetime(df['transaction_date'], format='mixed')

In [15]:
# Mengubah setting alphabet menjadi huruf kecil semua
df['make']=df['make'].str.lower()

In [16]:
df['make'].unique()

<StringArray>
[  'alfa-romero',          'audi',           'bmw',     'chevrolet',
         'dodge',       'dodge  ',         'honda',         'isuzu',
        'jaguar',         'mazda', 'mercedes-benz',     'mercury  ',
    'mitsubishi',        'nissan',        'peugot',        'toyota',
      'plymouth',       'porsche',     'porsche  ',       'renault',
          'saab',        'subaru',    'volkswagen',         'volvo']
Length: 24, dtype: str

In [17]:
# Menghilangkan spasi additional
df['make']=df['make'].str.strip()

In [18]:
df['make'].unique()

<StringArray>
[  'alfa-romero',          'audi',           'bmw',     'chevrolet',
         'dodge',         'honda',         'isuzu',        'jaguar',
         'mazda', 'mercedes-benz',       'mercury',    'mitsubishi',
        'nissan',        'peugot',        'toyota',      'plymouth',
       'porsche',       'renault',          'saab',        'subaru',
    'volkswagen',         'volvo']
Length: 22, dtype: str

In [19]:
df['fuel-system']=df['fuel-system'].str.lower()

In [20]:
df['fuel-system'].unique()

<StringArray>
['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', 'idi', 'spdi']
Length: 7, dtype: str

In [21]:
# Pisahkan bulan dan tahun pada kolom "transaction-date"
df['transaction_month']=df['transaction_date'].dt.month
df['transaction_year']=df['transaction_date'].dt.year
df.drop('transaction_date', axis=1, inplace=True)
df

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas,transaction_month,transaction_year
0,3,122,alfa-romero,std,2.0,convertible,rwd,front,88.6,0.811148,0.890278,48.8,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1,1,2025
1,3,122,alfa-romero,std,2.0,convertible,rwd,front,88.6,0.811148,0.890278,48.8,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1,2,2025
2,1,122,alfa-romero,std,2.0,hatchback,rwd,front,94.5,0.822681,0.909722,52.4,2823,ohcv,6,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1,1,2025
3,2,164,audi,std,4.0,sedan,fwd,front,99.8,0.848630,0.919444,54.3,2337,ohc,4,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1,1,2025
4,2,164,audi,std,4.0,sedan,4wd,front,99.4,0.848630,0.922222,54.3,2824,ohc,5,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1,1,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95,volvo,turbo,4.0,sedan,rwd,front,109.1,0.907256,0.956944,55.5,3217,ohc,6,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0,9.038462,Medium,1,0,7,2025
200,-1,95,volvo,turbo,4.0,sedan,rwd,front,109.1,0.907256,0.956944,55.5,3062,ohc,4,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0,12.368421,Medium,0,1,7,2025
201,2,122,audi,std,2.0,sedan,fwd,front,99.8,0.851994,0.920833,53.1,2507,ohc,5,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250.0,12.368421,Medium,0,1,6,2025
202,1,148,dodge,std,4.0,sedan,fwd,front,93.7,0.755887,0.886111,50.6,1989,ohc,4,90,2bbl,2.97,3.23,9.4,68.0,5500.0,31,38,7609.0,7.580645,Low,0,1,1,2025
203,0,122,mazda,std,4.0,sedan,fwd,front,98.8,0.854397,0.923611,55.5,2443,ohc,4,122,idi,3.39,3.39,22.7,64.0,4650.0,36,42,10795.0,6.527778,Low,1,0,3,2025

In [22]:
from sklearn.preprocessing import MinMaxScaler, OrdinalEncoder

In [23]:
from sklearn.preprocessing import MinMaxScaler, OrdinalEncoder

# 1. Ordinal Encoding: Untuk 'horsepower-binned'
# Asumsi urutan kategorinya adalah Low, Medium, High
ordinal_cols = ['horsepower-binned']
ord_encoder = OrdinalEncoder(categories=[['Low', 'Medium', 'High']])
df[ordinal_cols] = ord_encoder.fit_transform(df[ordinal_cols])

# 2. One-Hot Encoding: Menggunakan pandas get_dummies agar praktis
nominal_cols = ['make', 'aspiration', 'body-style', 'drive-wheels', 
                'engine-location', 'engine-type', 'fuel-system']
df = pd.get_dummies(df, columns=nominal_cols, drop_first=True, dtype=int)

# 3. Min-Max Scaling: Untuk semua kolom numerik kontinu
numeric_cols = ['normalized-losses', 'wheel-base', 'length', 'width', 'height', 
                'curb-weight', 'engine-size', 'bore', 'stroke', 'compression-ratio', 
                'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'city-L/100km']
                
scaler = MinMaxScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# Cek hasil akhir
print(df.head())

   symboling  normalized-losses  num-of-doors  wheel-base    length     width  \
0          3           0.298429           2.0    0.068966  0.450407  0.324786
1          3           0.298429           2.0    0.068966  0.450407  0.324786
2          1           0.298429           2.0    0.272414  0.489431  0.444444
3          2           0.518325           4.0    0.455172  0.577236  0.504274
4          2           0.518325           4.0    0.441379  0.577236  0.521368

     height  curb-weight  num-of-cylinders  engine-size      bore    stroke  \
0  0.000000     0.411171                 4     0.283951  0.664286  0.290476
1  0.000000     0.411171                 4     0.283951  0.664286  0.290476
2  0.327273     0.517843                 6     0.374486  0.100000  0.666667
3  0.500000     0.329325                 4     0.197531  0.464286  0.633333
4  0.500000     0.518231                 5     0.308642  0.464286  0.633333

   compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg    price  \
0             0.1250    0.396226  0.346939  0.200000     0.289474  13495.0
1             0.1250    0.396226  0.346939  0.200000     0.289474  16500.0
2             0.1250    0.666667  0.346939  0.142857     0.263158  16500.0
3             0.1875    0.339623  0.551020  0.285714     0.368421  13950.0
4             0.0625    0.421384  0.551020  0.114286     0.157895  17450.0

   city-L/100km  horsepower-binned  diesel  gas  transaction_month  \
0      0.533333                1.0       0    1                  1
1      0.533333                1.0       0    1                  2
2      0.631579                1.0       0    1                  1
3      0.416667                1.0       0    1                  1
4      0.688889                1.0       0    1                  1

   transaction_year  make_audi  make_bmw  make_chevrolet  make_dodge  \
0              2025          0         0               0           0
1              2025          0         0               0           0
2              2025          0         0               0           0
3              2025          1         0               0           0
4              2025          1         0               0           0

   make_honda  make_isuzu  make_jaguar  make_mazda  make_mercedes-benz  \
0           0           0            0           0                   0
1           0           0            0           0                   0
2           0           0            0           0                   0
3           0           0            0           0                   0
4           0           0            0           0                   0

   make_mercury  make_mitsubishi  make_nissan  make_peugot  make_plymouth  \
0             0                0            0            0              0
1             0                0            0            0              0
2             0                0            0            0              0
3             0                0            0            0              0
4             0                0            0            0              0

   make_porsche  make_renault  make_saab  make_subaru  make_toyota  \
0             0             0          0            0            0
1             0             0          0            0            0
2             0             0          0            0            0
3             0             0          0            0            0
4             0             0          0            0            0

   make_volkswagen  make_volvo  aspiration_turbo  body-style_Sedan  \
0                0           0                 0                 0
1                0           0                 0                 0
2                0           0                 0                 0
3                0           0                 0                 0
4                0           0                 0                 0

   body-style_convertible  body-style_hardtop  body-style_hatchback  \
0                       1                   0                     0
1                       1                   0                     0
2                       0                   0                     1
3                       0                   0                     0
4                       0                   0                     0

   body-style_sedan  body-style_wagon  drive-wheels_AWD  drive-wheels_RWD  \
0                 0                 0                 0                 0
1                 0                 0                 0                 0
2                 0                 0                 0                 0
3                 1                 0                 0                 0
4                 1                 0                 0                 0

   drive-wheels_fwd  drive-wheels_rwd  engine-location_rear  engine-type_l  \
0                 0                 1                     0              0
1                 0                 1                     0              0
2                 0                 1                     0              0
3                 1                 0                     0              0
4                 0                 0                     0              0

   engine-type_ohc  engine-type_ohcf  engine-type_ohcv  fuel-system_2bbl  \
0                0                 0                 0                 0
1                0                 0                 0                 0
2                0                 0                 1                 0
3                1                 0                 0                 0
4                1                 0                 0                 0

   fuel-system_idi  fuel-system_mfi  fuel-system_mpfi  fuel-system_spdi  \
0                0                0                 1                 0
1                0                0                 1                 0
2                0                0                 1                 0
3                0                0                 1                 0
4                0                0                 1                 0

   fuel-system_spfi
0                 0
1                 0
2                 0
3                 0
4                 0

In [24]:
display(df)

,symboling,normalized-losses,num-of-doors,wheel-base,length,width,height,curb-weight,num-of-cylinders,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas,transaction_month,transaction_year,make_audi,make_bmw,make_chevrolet,make_dodge,make_honda,make_isuzu,make_jaguar,make_mazda,make_mercedes-benz,make_mercury,make_mitsubishi,make_nissan,make_peugot,make_plymouth,make_porsche,make_renault,make_saab,make_subaru,make_toyota,make_volkswagen,make_volvo,aspiration_turbo,body-style_Sedan,body-style_convertible,body-style_hardtop,body-style_hatchback,body-style_sedan,body-style_wagon,drive-wheels_AWD,drive-wheels_RWD,drive-wheels_fwd,drive-wheels_rwd,engine-location_rear,engine-type_l,engine-type_ohc,engine-type_ohcf,engine-type_ohcv,fuel-system_2bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi
0,3,0.298429,2.0,0.068966,0.450407,0.324786,0.000000,0.411171,4,0.283951,0.664286,0.290476,0.12500,0.396226,0.346939,0.200000,0.289474,13495.0,0.533333,1.0,0,1,1,2025,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
1,3,0.298429,2.0,0.068966,0.450407,0.324786,0.000000,0.411171,4,0.283951,0.664286,0.290476,0.12500,0.396226,0.346939,0.200000,0.289474,16500.0,0.533333,1.0,0,1,2,2025,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
2,1,0.298429,2.0,0.272414,0.489431,0.444444,0.327273,0.517843,6,0.374486,0.100000,0.666667,0.12500,0.666667,0.346939,0.142857,0.263158,16500.0,0.631579,1.0,0,1,1,2025,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0
3,2,0.518325,4.0,0.455172,0.577236,0.504274,0.500000,0.329325,4,0.197531,0.464286,0.633333,0.18750,0.339623,0.551020,0.285714,0.368421,13950.0,0.416667,1.0,0,1,1,2025,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0
4,2,0.518325,4.0,0.441379,0.577236,0.521368,0.500000,0.518231,5,0.308642,0.464286,0.633333,0.06250,0.421384,0.551020,0.114286,0.157895,17450.0,0.688889,1.0,0,1,1,2025,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,0.157068,4.0,0.775862,0.775610,0.735043,0.609091,0.670675,6,0.345679,0.335714,0.633333,1.00000,0.364780,0.265306,0.342857,0.289474,22470.0,0.353846,1.0,1,0,7,2025,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0
200,-1,0.157068,4.0,0.775862,0.775610,0.735043,0.609091,0.610551,4,0.329218,0.885714,0.514286,0.15625,0.415094,0.510204,0.142857,0.236842,22625.0,0.631579,1.0,0,1,7,2025,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0
201,2,0.298429,2.0,0.455172,0.588618,0.512821,0.390909,0.395268,5,0.308642,0.464286,0.633333,0.09375,0.389937,0.551020,0.142857,0.236842,15250.0,0.631579,1.0,0,1,6,2025,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0
202,1,0.434555,4.0,0.244828,0.263415,0.299145,0.163636,0.194337,4,0.119342,0.307143,0.552381,0.15000,0.125786,0.551020,0.485714,0.578947,7609.0,0.232258,0.0,0,1,1,2025,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0
203,0,0.298429,4.0,0.420690,0.596748,0.529915,0.609091,0.370442,4,0.251029,0.607143,0.628571,0.98125,0.100629,0.204082,0.628571,0.684211,10795.0,0.144444,0.0,1,0,3,2025,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0